Adds the best attendee to the front page
theantievent/theantievent pull request #3
Opened 2022-09-14 08:58 UTC by Viroide

![I deserve](https://media3.giphy.com/media/b5WTou0NsI7CwDC1Ev/giphy.gif?cid=f3f3e2aaqdqwuzgbp7qipk7pbtk1o6tlgr4exgkomjycqh7a&rid=giphy.gif&ct=g)

2022-09-14 14:19 UTC, ibaiimaz reviewed
With this profile picture you can't say no

2022-09-16 16:15 UTC, nabaroa requested changes

2022-09-16 16:15 UTC, nabaroa commented on docs/js/attendees-list.json
>    }
@Viroide could you replace Carmen's spot, please? She is not going to join us 😢

2022-09-16 16:22 UTC, nabaroa approved these changes

2022-09-16 16:22 UTC, merged